version: "3.2"
services:
  nginx_server:
    build:
      context: ./conf/nginx
      dockerfile: Dockerfile
    depends_on:
      - tgfront
    networks:
      - main_net
    ports:
      - '80:80'
      - '443:443'

  tgfront:
    build:
      context: ./tg-front
      dockerfile: Dockerfile
    networks:
      - main_net
    environment:
      - EATSMART_API_URL=https://eat-smart.ru
      - EATSMART_HOME_URL=https://t.me/eat_smart_bot

  fbotapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - main_net

networks:
  main_net:
    driver: bridge
